version: '3.1'
services:
  humhub:
    image: mriedmann/humhub:1.6.2
    ports:
      - "8080:80"
    volumes:
      - "./config:/var/www/localhost/htdocs/protected/config"
      - "./uploads:/var/www/localhost/htdocs/uploads"
      - "./modules:/var/www/localhost/htdocs/protected/modules"
      - "./patch/showFiles.php:/var/www/localhost/htdocs/protected/humhub/modules/file/widgets/views/showFiles.php:ro"
    environment:
      HUMHUB_DB_USER: humhub
      HUMHUB_DB_PASSWORD: humhub
      SET_PJAX: "true"
      PHP_POST_MAX_SIZE: "2G"
      PHP_UPLOAD_MAX_FILESIZE: "2G"
      # set internal nginx client max body size to unlimited
      NGINX_CLIENT_MAX_BODY_SIZE: "0"
    restart: always
    depends_on:
      - db

  db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: humhub
      MYSQL_USER: humhub
      MYSQL_PASSWORD: humhub
    restart: always
    volumes:
      - "./db/:/var/lib/mysql"
